/**
 * Pin Class
 * Represents a single connection point (Input or Output) on a Node.
 * It holds configuration (name, type), runtime state (value), and the associated Widget Model (if any).
 * This class acts as the "Model" for a Pin. The "View" is generated by NodeRenderer.js.
 */
class Pin {
    /**
     * Creates a new Pin instance.
     * @param {GraphNode} parentNode - The Node instance that owns this pin.
     * @param {Number} pinIndex - The index of this pin in the node's inputs or outputs array.
     * @param {String} pinDirection - The direction of data flow ('input' or 'output').
     * @param {Object} pinTemplate - The JSON definition for this pin (derived from the Node template).
     */
    constructor(parentNode, pinIndex, pinDirection, pinTemplate) {
        this.node = parentNode;
        this.nodeId = parentNode.id;
        this.index = pinIndex;
        this.direction = pinDirection;
        
        this.name = pinTemplate.name;
        this.type = pinTemplate.type;
        this.dataType = pinTemplate.type; // Tracks the current type (mutable for generic pins)
        
        this.advanced = pinTemplate.advanced || false;
        this.allowedTypes = pinTemplate.allowedTypes || null; 
        
        this.widget = null; // The UI control associated with this pin (if any)
        this.value = null;  // The runtime value of the pin

        // Only input pins typically have interactive widgets (like text boxes)
        if (pinDirection === 'input') {
            this.initializeWidget(pinTemplate);
        }
    }

    /**
     * Sets up the interactive widget (UI control) for this pin based on its type.
     * @param {Object} pinTemplate - The configuration object for the pin.
     */
    initializeWidget(pinTemplate) {
        // Check if there is a global definition for this type that specifies a default widget
        const globalTypeDefinition = window.typeDefinitions ? window.typeDefinitions[this.type] : null;
        
        // Determine widget type: Priority is Explicit Template > Global Type Default > None
        const widgetType = pinTemplate 
            ? (pinTemplate.widget || (globalTypeDefinition ? globalTypeDefinition.widget : 'none')) 
            : (globalTypeDefinition ? globalTypeDefinition.widget : 'none');

        if (widgetType && widgetType !== 'none') {
            const definedDefault = pinTemplate ? pinTemplate.default : undefined;
            const finalDefaultValue = this.resolveDefaultValue(this.type, definedDefault);
            
            // Create the Widget Model
            this.widget = new Widget(widgetType, finalDefaultValue, pinTemplate ? pinTemplate.options : []);
            this.value = finalDefaultValue;
        } else {
            this.widget = null;
        }
    }

    /**
     * Changes the pin's data type dynamically and resets its value.
     * Useful for "Wildcard" pins that adapt to the connected wire's type.
     * @param {String} newDataType - The new data type identifier.
     */
    setType(newDataType) {
        this.type = newDataType;
        this.dataType = newDataType;
        
        if (this.direction === 'input') {
            // Re-run widget initialization with null template to force type-based defaults
            this.initializeWidget(null);
        } else {
            this.value = this.resolveDefaultValue(newDataType);
        }
    }

    /**
     * Helper to determine the initial value for a pin based on its type.
     * @param {String} typeIdentifier - The data type of the pin.
     * @param {any} manualDefaultValue - A specific default provided in the JSON (optional).
     * @returns {any} The resolved default value.
     */
    resolveDefaultValue(typeIdentifier, manualDefaultValue) {
        // If a specific default was provided in the template, use it.
        if (manualDefaultValue !== undefined) return manualDefaultValue;
        
        // Otherwise, return a safe default for the specific type
        switch (typeIdentifier) {
            case 'string': return "Hello World";
            case 'float': return 0.0;
            case 'int': return 0;
            case 'boolean': return true;
            case 'color': return "#FFFFFF";
            case 'vector': return {x:0, y:0, z:0};
            case 'class': return "None";
            case 'object': return "None";
            default: return null;
        }
    }
}