/**
 * Node Class
 * Represents a single logical node in the graph.
 * It holds the state (position, expanded/collapsed), configuration (name, color),
 * and lists of Input/Output Pins.
 * This is the "Model". The "View" is generated by NodeRenderer.js.
 */
class GraphNode {
    /**
     * @param {Number} id - Unique ID generated by the Graph.
     * @param {Object} template - The JSON definition for this node type (from Nodes.js).
     * @param {Number} x - X position on the canvas.
     * @param {Number} y - Y position on the canvas.
     */
    constructor(id, template, x, y) {
        this.id = id;
        this.x = x;
        this.y = y;
        
        // Node Configuration
        this.name = template.name;
        this.color = template.color || "var(--header-bg)";
        this.width = template.width; // Optional override for node width
        
        // Layout Flags
        this.hideHeader = template.hideHeader || false; // Used for "Compact" nodes (like Math)
        this.centerLabel = template.centerLabel || null; // Used for Math symbols (+, -, etc)
        
        // State: Tracks if "Advanced" pins are currently visible
        this.showAdvanced = false;

        // Function Binding (Execution Logic)
        this.functionId = template.functionId || null;
        this.jsFunctionRef = window.FunctionRegistry ? window.FunctionRegistry[this.functionId] : null;
        this.executionResult = null; // Cache for Pure node results

        // Instantiate Pin Models
        this.inputs = (template.inputs || []).map((p, i) => new Pin(this, i, 'input', p));
        this.outputs = (template.outputs || []).map((p, i) => new Pin(this, i, 'output', p));
    }

    /**
     * Helper to retrieve data from a specific input pin.
     * Currently returns the value from the Widget (text box, checkbox, etc).
     * @param {Number} index - The index of the input pin.
     * @returns {any} The value, or null if invalid.
     */
    getInputValue(index) {
        if (!this.inputs[index]) return null;
        if (this.inputs[index].widget) {
            return this.inputs[index].widget.value;
        }
        return null; 
    }
    
    /**
     * Checks if this node contains any pins marked as 'advanced'.
     * Used by NodeRenderer to decide if the Expansion Arrow should be drawn.
     * @returns {Boolean}
     */
    hasAdvancedPins() {
        return this.inputs.some(p => p.advanced) || this.outputs.some(p => p.advanced);
    }

    /**
     * Displays or hides an error message on the node UI.
     * @param {String|null} msg - The error message to display, or null to clear.
     */
    setError(msg) {
        const el = document.getElementById(`node-${this.id}`);
        if (!el) return;
        
        let errDiv = el.querySelector('.node-error');
        if (!msg) {
            if (errDiv) errDiv.style.display = 'none';
            el.classList.remove('has-error');
            return;
        }

        if (!errDiv) {
            errDiv = document.createElement('div');
            errDiv.className = 'node-error';
            el.appendChild(errDiv);
        }
        errDiv.innerText = msg;
        errDiv.style.display = 'block';
        el.classList.add('has-error');
    }

    /**
     * Serializes the node state for Copy/Paste or Saving.
     * Captures position, template identifier, current input widget values, AND active pin types.
     * @returns {Object} JSON-safe object.
     */
    toJSON() {
        return {
            id: this.id, // Needed for connection mapping during full save
            name: this.name, // Template Name identifier
            x: this.x,
            y: this.y,
            // Persist current pin types to restore polymorphic state
            pinTypes: {
                inputs: this.inputs.map(p => p.type),
                outputs: this.outputs.map(p => p.type)
            },
            // Save Input values (widgets)
            inputs: this.inputs.map(p => ({
                name: p.name,
                value: p.value 
            }))
        };
    }
}