/**
 * Pin Class
 * Represents a single connection point (Input or Output) on a Node.
 * It holds configuration (name, type), state (value), and the associated Widget Model (if any).
 * This is the "Model" for a Pin. The "View" is generated by NodeRenderer.js.
 */
class Pin {
    /**
     * @param {Node} node - The parent Node instance.
     * @param {Number} index - The index of this pin in the inputs/outputs array.
     * @param {String} direction - 'input' or 'output'.
     * @param {Object} template - The JSON definition for this pin (from Nodes.js).
     */
    constructor(node, index, direction, template) {
        this.node = node;
        this.nodeId = node.id;      // Cached ID for easier DOM/Interaction lookups
        this.index = index;
        this.direction = direction; // 'input' or 'output'
        
        // Pin Metadata
        this.name = template.name;
        this.type = template.type;      // e.g., 'exec', 'string', 'vector'
        this.dataType = template.type;  // Alias used for compatibility checking
        this.advanced = template.advanced || false; // If true, pin is hidden inside "Advanced" fold
        
        // --- Widget Initialization ---
        this.widget = null;
        this.value = null; // Stores the local value (used when not connected)

        // Only Input pins can have widgets (controls like textboxes/checkboxes)
        if (direction === 'input') {
            // 1. Lookup Global Type Definition (for default colors/widgets)
            const typeDef = window.typeDefinitions ? window.typeDefinitions[this.type] : null;
            
            // 2. Determine Widget Type
            // Priority: Explicit 'widget' in Node JSON > Default 'widget' in DataTypes.js > 'none'
            const widgetType = template.widget || (typeDef ? typeDef.widget : 'none');

            // 3. Instantiate Widget Model if valid
            if (widgetType && widgetType !== 'none') {
                const defaultValue = this.getDefaultValue(this.type, template.default);
                
                // Create the Widget Model (holds options for dropdowns, current value, etc.)
                this.widget = new Widget(widgetType, defaultValue, template.options);
                
                // Sync Pin value with Widget value immediately
                this.value = defaultValue;
            }
        }
    }

    /**
     * Helper to determine the initial value for a pin.
     * @param {String} type - The data type of the pin.
     * @param {any} manualDefault - A specific default provided in the JSON (optional).
     * @returns {any} The resolved default value.
     */
    getDefaultValue(type, manualDefault) {
        // If the JSON explicitly defines a default, use it.
        if (manualDefault !== undefined) return manualDefault;

        // Otherwise, return a sensible default based on the Data Type
        switch (type) {
            case 'string': return "Hello World";
            case 'float': return 0.0;
            case 'int': return 0;
            case 'boolean': return true;
            case 'color': return "#FFFFFF";
            case 'vector': return {x:0, y:0, z:0};
            case 'class': return "None";
            case 'object': return "None";
            default: return null;
        }
    }
}