/**
 * Pin Class
 * Represents a single connection point (Input or Output) on a Node.
 * It holds configuration (name, type), state (value), and the associated Widget Model (if any).
 * This is the "Model" for a Pin. The "View" is generated by NodeRenderer.js.
 */
class Pin {
    /**
     * @param {Node} node - The parent Node instance.
     * @param {Number} index - The index of this pin in the inputs/outputs array.
     * @param {String} direction - 'input' or 'output'.
     * @param {Object} template - The JSON definition for this pin (from Nodes.js).
     */
    constructor(node, index, direction, template) {
        this.node = node;
        this.nodeId = node.id;
        this.index = index;
        this.direction = direction;
        
        this.name = template.name;
        this.type = template.type;
        this.dataType = template.type;
        this.advanced = template.advanced || false;
        this.allowedTypes = template.allowedTypes || null; 
        
        this.widget = null;
        this.value = null; 

        if (direction === 'input') {
            this.initWidget(template);
        }
    }

    initWidget(template) {
        const typeDef = window.typeDefinitions ? window.typeDefinitions[this.type] : null;
        // Priority: Explicit widget > Type Default widget > None
        const widgetType = template ? (template.widget || (typeDef ? typeDef.widget : 'none')) : (typeDef ? typeDef.widget : 'none');

        if (widgetType && widgetType !== 'none') {
            const defVal = template ? template.default : undefined;
            const defaultValue = this.getDefaultValue(this.type, defVal);
            this.widget = new Widget(widgetType, defaultValue, template ? template.options : []);
            this.value = defaultValue;
        } else {
            this.widget = null;
        }
    }

    /**
     * Changes the pin type and resets its value to the new type's default.
     * Re-initializes the widget model if the type implies a different widget (e.g. float -> vector).
     * @param {String} newType - The new data type identifier.
     */
    setType(newType) {
        this.type = newType;
        this.dataType = newType;
        
        if (this.direction === 'input') {
            // Re-run widget initialization with null template to force type-based defaults
            this.initWidget(null);
        } else {
            this.value = this.getDefaultValue(newType);
        }
    }

    /**
     * Helper to determine the initial value for a pin.
     * @param {String} type - The data type of the pin.
     * @param {any} manualDefault - A specific default provided in the JSON (optional).
     * @returns {any} The resolved default value.
     */
    getDefaultValue(type, manualDefault) {
        if (manualDefault !== undefined) return manualDefault;
        switch (type) {
            case 'string': return "Hello World";
            case 'float': return 0.0;
            case 'int': return 0;
            case 'boolean': return true;
            case 'color': return "#FFFFFF";
            case 'vector': return {x:0, y:0, z:0};
            case 'class': return "None";
            case 'object': return "None";
            default: return null;
        }
    }
}